import React from "react";
import { useSearchParams } from "react-router-dom";
import { ArrowLeft, IndianRupee, AlertTriangle, MoveRight } from "lucide-react";

export default function QrPayment() {
  const [searchParams] = useSearchParams();

  const name = searchParams.get("name");
  const totalAmount = searchParams.get("amount");

  if (!name || !totalAmount) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-red-600 font-semibold">
          Invalid payment link. Please go back and try again.
        </p>
      </div>
    );
  }
async function handelpayment(){
try {
  window.open(
  `https://hackthon-backend-1-d2zj.onrender.com/singel/payment?name=${name}`,
  "_blank"
);
} catch (error) {
  alert(error)
  console.log(error)
}
}
  return (
    <div className="w-full min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full bg-white rounded-2xl shadow-xl p-6">

        <div className="flex items-center gap-3 mb-6">
         

          <h1 className="text-2xl font-bold text-[#0f2027]">
            Payment Verification
          </h1>
        </div>

        <div className="text-center mb-6">
          <p className="text-gray-500 text-sm">Name</p>
          <p className="text-lg font-semibold text-[#0f2027]">
            {name}
          </p>

          <p className="text-gray-500 text-sm mt-4">Amount to Pay</p>
          <div className="flex justify-center items-center gap-2 text-4xl font-bold text-[#0f2027]">
            <IndianRupee size={28} />
            <span>{totalAmount}</span>
          </div>
          <button
  onClick={handelpayment}
  className="
    mt-6
    inline-flex items-center gap-2
    px-6 py-3
    rounded-xl
    bg-gradient-to-r from-[#0f2027] to-[#203a43]
    text-white font-semibold
    shadow-lg
    hover:shadow-xl
    hover:scale-[1.02]
    active:scale-95
    transition-all duration-200
  "
>
  <MoveRight className="w-5 h-5" />
  Pay
</button>

        </div>

        <div className="mb-6 bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-lg">
          <div className="flex items-start gap-2">
            <AlertTriangle className="text-yellow-600 mt-0.5" size={18} />
            <div className="text-sm text-yellow-800 space-y-2">
              <p className="font-semibold">Please verify before proceeding:</p>
              <ul className="list-disc list-inside space-y-1">
                <li>Confirm this is your name</li>
                <li>Ensure the amount is correct</li>
                <li>Payment page is generated by our server</li>
                <li>Do not refresh during payment</li>
              </ul>
            </div>
          </div>
        </div>

        <p className="text-xs text-gray-500 text-center">
          After payment, submit the transaction number for verification.
        </p>
      </div>
    </div>
  );
}
