  const problems = [
    {
      id: 1,
      title: "Smart Healthcare Monitoring System",
      category: "Healthcare",
      difficulty: "Medium",
      points: 100,
      description:
        "Develop an AI-powered healthcare monitoring system that tracks patient vitals in real-time and provides predictive analytics for early disease detection.",
      tags: ["AI", "IoT", "Real-time", "Predictive Analytics"],
      requirements: [
        "Real-time vital signs monitoring (heart rate, blood pressure, temperature, oxygen levels)",
        "AI-based anomaly detection and automated alert system",
        "Patient history tracking and trend analysis with visualization",
        "Dashboard interface for healthcare providers with role-based access",
        "Mobile application for patients to view their health data",
      ],
      deliverables: [
        "Working prototype with IoT sensor integration",
        "Trained AI model for health prediction and anomaly detection",
        "Web dashboard and mobile interface",
        "Complete technical documentation and user guide",
        "Final presentation with live demo",
      ],
      technologies: ["Python", "TensorFlow", "React", "IoT Sensors", "Firebase", "Node.js"],
    },
    {
      id: 2,
      title: "Sustainable Energy Management Platform",
      category: "Sustainability",
      difficulty: "Hard",
      points: 150,
      description:
        "Create a comprehensive platform for monitoring and optimizing energy consumption in smart buildings using IoT sensors and machine learning algorithms.",
      tags: ["IoT", "Machine Learning", "Green Tech", "Energy Optimization"],
      requirements: [
        "Real-time energy consumption monitoring with IoT sensor integration",
        "Machine learning model for energy consumption prediction",
        "Automated energy optimization recommendations based on usage patterns",
        "Integration with smart devices for automated control",
        "Carbon footprint calculator and environmental impact dashboard",
      ],
      deliverables: [
        "IoT-enabled energy monitoring system with sensor integration",
        "Trained ML model for consumption prediction",
        "Interactive dashboard with data visualization and analytics",
        "Mobile application for end users",
        "API documentation and deployment guide",
      ],
      technologies: ["Node.js", "Python", "IoT Devices", "Scikit-learn", "Chart.js", "MongoDB", "MQTT"],
    },
    {
      id: 3,
      title: "Cybersecurity Threat Detection System",
      category: "Cybersecurity",
      difficulty: "Hard",
      points: 150,
      description:
        "Build an intelligent system that detects and prevents cyber threats using machine learning and real-time network traffic analysis.",
      tags: ["Security", "Machine Learning", "Network Analysis", "Threat Intelligence"],
      requirements: [
        "Real-time network traffic monitoring and packet analysis",
        "ML-based threat detection using supervised and unsupervised learning",
        "Automated incident response system with configurable actions",
        "Threat intelligence dashboard with visual analytics",
        "Alert and notification system with severity classification",
      ],
      deliverables: [
        "Threat detection engine with ML models",
        "Network traffic analysis module",
        "Real-time monitoring dashboard with threat visualization",
        "Incident response automation workflow",
        "Security report generation system",
      ],
      technologies: ["Python", "Scikit-learn", "Wireshark", "React", "PostgreSQL", "Redis", "Flask"],
    },
    {
      id: 4,
      title: "Interactive EdTech Learning Platform",
      category: "EdTech",
      difficulty: "Medium",
      points: 100,
      description:
        "Develop an engaging educational platform with gamification elements, personalized learning paths, and AI-powered assessments to enhance student learning outcomes.",
      tags: ["Education", "AI", "Gamification", "Personalization"],
      requirements: [
        "Personalized learning path generation based on student performance",
        "Gamification elements including badges, points, and leaderboards",
        "AI-based question generation and adaptive assessments",
        "Progress tracking and detailed analytics for students and teachers",
        "Interactive content delivery with multimedia support",
      ],
      deliverables: [
        "Web platform with user management and authentication",
        "AI-powered content recommendation engine",
        "Gamification system with reward mechanisms",
        "Analytics dashboard for educators",
        "Mobile-responsive interface",
      ],
      technologies: ["React", "Node.js", "MongoDB", "OpenAI API", "WebSocket", "Redux"],
    },
    {
      id: 5,
      title: "AI-Powered Financial Assistant",
      category: "AI/ML",
      difficulty: "Medium",
      points: 100,
      description:
        "Create an intelligent financial assistant that helps users manage budgets, track expenses, and provides personalized investment recommendations using AI.",
      tags: ["AI", "Finance", "Analytics", "Personal Finance"],
      requirements: [
        "Automated expense tracking and smart categorization",
        "Budget planning with predictive alerts and recommendations",
        "AI-based spending pattern analysis and insights",
        "Investment recommendation engine based on risk profile",
        "Financial health score calculation with improvement suggestions",
      ],
      deliverables: [
        "Mobile and web application with seamless sync",
        "AI recommendation system for financial decisions",
        "Interactive data visualization dashboard",
        "Secure authentication and data encryption",
        "Integration with banking APIs",
      ],
      technologies: ["React Native", "Python", "TensorFlow", "Firebase", "Plaid API", "Chart.js"],
    },
    {
      id: 6,
      title: "Smart City Traffic Management",
      category: "IoT",
      difficulty: "Hard",
      points: 150,
      description:
        "Design an intelligent traffic management system using IoT sensors and AI algorithms to optimize traffic flow, reduce congestion, and improve urban mobility.",
      tags: ["IoT", "AI", "Smart City", "Optimization"],
      requirements: [
        "Real-time traffic monitoring using IoT sensors and cameras",
        "AI-based traffic flow prediction and congestion analysis",
        "Dynamic traffic signal timing optimization algorithm",
        "Emergency vehicle priority routing system",
        "Citizen reporting integration for accidents and road conditions",
      ],
      deliverables: [
        "IoT sensor network simulation with data collection",
        "AI optimization algorithm for traffic management",
        "Real-time traffic management dashboard",
        "Mobile app for citizens with live updates",
        "API for third-party integrations",
      ],
      technologies: ["Python", "IoT Sensors", "TensorFlow", "React", "Google Maps API", "MQTT"],
    },
    {
      id: 7,
      title: "Social Media Analytics Platform",
      category: "Web Development",
      difficulty: "Easy",
      points: 75,
      description:
        "Build a comprehensive analytics platform that tracks social media metrics, performs sentiment analysis, and identifies engagement trends across multiple platforms.",
      tags: ["Analytics", "API Integration", "Data Visualization", "NLP"],
      requirements: [
        "Multi-platform social media integration (Twitter, Instagram, Facebook)",
        "Sentiment analysis of posts and comments using NLP",
        "Engagement metrics tracking (likes, shares, comments, reach)",
        "Trend identification and hashtag analysis",
        "Customizable reports with export functionality",
      ],
      deliverables: [
        "Web-based analytics dashboard",
        "Social media API integrations",
        "Interactive data visualization charts",
        "PDF/Excel export functionality",
        "Scheduled reporting system",
      ],
      technologies: ["React", "Node.js", "Chart.js", "Twitter API", "Natural Language Toolkit", "PostgreSQL"],
    },
    {
      id: 8,
      title: "AR-Based Shopping Experience",
      category: "Mobile App",
      difficulty: "Hard",
      points: 150,
      description:
        "Create an innovative augmented reality shopping application that allows users to visualize products in their physical space before making a purchase decision.",
      tags: ["AR", "E-commerce", "Mobile", "3D Visualization"],
      requirements: [
        "AR product visualization with realistic rendering",
        "3D product model integration and management",
        "Virtual try-on features for different product categories",
        "Complete shopping cart and secure checkout process",
        "User reviews and ratings system with photo uploads",
      ],
      deliverables: [
        "Mobile AR application (iOS/Android)",
        "Interactive 3D model viewer with AR capabilities",
        "E-commerce backend integration",
        "Product catalog management system",
        "User experience demo video",
      ],
      technologies: ["Unity", "ARCore/ARKit", "Firebase", "Blender", "React Native", "Node.js"],
    },
  ]

  const categories = [
    "All",
    "AI/ML",
    "Web Development",
    "Mobile App",
    "Cybersecurity",
    "Healthcare",
    "IoT",
    "Sustainability",
    "EdTech",
  ]
  const difficulties = ["All", "Easy", "Medium", "Hard"]
export {problems,categories,difficulties}